image:
  file: .gitpod.Dockerfile
tasks:
  - name: Virtualenv and Dependencies
    before: pip3 install virtualenv
    init: |
      virtualenv .venv
      echo "source /workspace/custom_homepluscontrol/.venv/bin/activate" >> ~/.bashrc
      source /workspace/custom_homepluscontrol/.venv/bin/activate
      pip3 install -r requirements_dev.txt
ports:
  - port: 8123
    onOpen: notify
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - ms-python.python
